- name: Install locale packages
  ansible.builtin.package:
    name:
      - language-pack-ja-base
      - language-pack-ja
      - ibus-mozc
      - manpages-ja-dev
      - manpages-ja
    state: present

- name: "set-locale"
  shell: update-locale LANG=ja_JP.UTF-8

# Ubuntu Japanese Teamリポジトリを追加する
- name: set ubuntu-ja-archive gpg key
  apt_key:
    url: "https://www.ubuntulinux.jp/ubuntu-ja-archive-keyring.gpg"
    state: present

- name: set ubuntu-jp-ppa-keyring gpg key
  apt_key:
    url: "https://www.ubuntulinux.jp/ubuntu-jp-ppa-keyring.gpg"
    state: present

- name: "ubuntu-ja repo set"
  get_url:
    url: "https://www.ubuntulinux.jp/sources.list.d/bionic.list"
    dest: /etc/apt/sources.list.d/ubuntu-ja.list
    owner: root
    group: root
    mode: 0644
