- name: Install locale packages
  ansible.builtin.package:
    name:
      - language-pack-ja-base
      - language-pack-ja
      - ibus-mozc
      - manpages-ja-dev
      - manpages-ja
    state: present

- name: "set-locale"
  shell: update-locale LANG=ja_JP.UTF-8

- name: "ubuntu-ja repo setting delete"
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/ubuntu-ja.list
    state: absent