# Debian・Ubuntu向け設定
- block:
  - name: apt install locale packages
    apt:
      name: "{{ packages }}"
      update_cache: yes
      cache_valid_time: 3600
      state: present
    vars:
      packages:
        - language-pack-ja-base
        - language-pack-ja
        - ibus-mozc
        - manpages-ja-dev
        - manpages-ja

  - name: "set-locale"
    shell: update-locale LANG=ja_JP.UTF-8

  # Ubuntu Japanese Teamリポジトリを追加する
  - name: set ubuntu-ja-archive gpg key
    apt_key:
      url: "https://www.ubuntulinux.jp/ubuntu-ja-archive-keyring.gpg"
      state: present

  - name: set ubuntu-jp-ppa-keyring gpg key
    apt_key:
      url: "https://www.ubuntulinux.jp/ubuntu-jp-ppa-keyring.gpg"
      state: present

  - name: "ubuntu-ja repo set"
    get_url:
      url: "https://www.ubuntulinux.jp/sources.list.d/bionic.list"
      dest: /etc/apt/sources.list.d/ubuntu-ja.list
      owner: root
      group: root
      mode: 0644

  # Debian・Ubuntu向け設定ここまで
  when: "ansible_os_family == 'Debian'"

# CentOS向け設定
- block:
  - name: "install ibus-kkc"
    package:
      name: "ibus-kkc"
      state: present

  - name: "install vlgothic-*"
    package:
      name: "vlgothic-*"
      state: present

  # 日本語の設定
  # - name: "set-locale"
  #  command: localectl set-locale LANG=ja_JP.UTF-8

  - name: "localedef"
    command: localedef -f UTF-8 -i ja_JP ja_JP.UTF-8
    check_mode: no

  - name: "set ja_JP to /etc/locale.conf"
    command: bash -c "echo 'LANG="ja_JP.UTF-8"' > /etc/locale.conf"
    check_mode: no

  - name: "set ja_JP"
    command: bash -c "source /etc/locale.conf"
    check_mode: no

  # CentOS向けここまで
  when: "ansible_os_family == 'RedHat'"
